### ISSUE TITLE
Stop working after updating to the latest version

### ISSUE THREAD

**Issue by nekohasekai** [Mygod/VPNHotspot#181]
device: Redmi Redmi K30 5G (miui 12)

```
java.io.EOFException
	at be.mygod.librootkotlinx.RootServer.lookForToken(RootServer.kt:125)
	at be.mygod.librootkotlinx.RootServer.doInit(RootServer.kt:159)
	at be.mygod.librootkotlinx.RootServer.access$doInit(RootServer.kt:25)
	at be.mygod.librootkotlinx.RootServer$init$2.invokeSuspend(RootServer.kt:199)
	at (Coroutine boundary.()
	at kotlinx.coroutines.CompletableDeferredImpl.await(CompletableDeferred.kt:87)
	at be.mygod.librootkotlinx.RootServer.init(RootServer.kt:225)
	at be.mygod.vpnhotspot.root.RootManager.initServer(RootManager.kt:43)
	at be.mygod.librootkotlinx.RootSession.ensureServerLocked(RootSession.kt:34)
	at be.mygod.librootkotlinx.RootSession$acquire$2.invokeSuspend(RootSession.kt:73)
	at be.mygod.vpnhotspot.SettingsPreferenceFragment$onCreatePreferences$5$1.invokeSuspend(SettingsPreferenceFragment.kt:160)
Caused by: java.io.EOFException
	at be.mygod.librootkotlinx.RootServer.lookForToken(RootServer.kt:125)
	at be.mygod.librootkotlinx.RootServer.doInit(RootServer.kt:159)
	at be.mygod.librootkotlinx.RootServer.access$doInit(RootServer.kt:25)
	at be.mygod.librootkotlinx.RootServer$init$2.invokeSuspend(RootServer.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Mygod** [comment]
Hmm do you happen to have superuser log?

**Comment by Mygod** [comment]
Otherwise, exporting debug information might help too.

**Comment by Mygod** [comment]
See if this works: https://mygod.be/resources/userscloud/anay6dl33p3m

**Comment by Mygod** [comment]
If it does not work, also try v2.10.13: https://github.com/Mygod/VPNHotspot/releases/tag/v2.10.13

**Comment by nekohasekai** [comment]
> Hmm do you happen to have superuser log?

Yes, every time I open the app

> See if this works: https://mygod.be/resources/userscloud/anay6dl33p3m

same

[vpnhotspot-6412671506064749573.log](https://github.com/Mygod/VPNHotspot/files/5049880/vpnhotspot-6412671506064749573.log)

> If it does not work, also try v2.10.13: https://github.com/Mygod/VPNHotspot/releases/tag/v2.10.13

Yes, 2.10.13 works normally

**Comment by Mygod** [comment]
Thanks. Could you try this again?

https://mygod.be/resources/userscloud/hj10ti9d1nof

**Comment by nekohasekai** [comment]
> Thanks. Could you try this again?
> 
> https://mygod.be/resources/userscloud/hj10ti9d1nof



> Thanks. Could you try this again?
> 
> https://mygod.be/resources/userscloud/hj10ti9d1nof

It shows no permission to read /proc/net/arp

[vpnhotspot-5611336581100378441.log](https://github.com/Mygod/VPNHotspot/files/5054324/vpnhotspot-5611336581100378441.log)

**Comment by Mygod** [comment]
Sorry for the trouble. This is one confusing bug for me.

Please try this nightly-3: https://userscloud.com/9rep4hb7oxk3

**Comment by Mygod** [comment]
Also these two:

* nightly-4: https://mygod.be/resources/userscloud/f790e2hm9s5o
* nightly-5: https://mygod.be/resources/userscloud/8ppdvh4q5yer

It would be great if you can test these three, and tell me whether each works, and export debug info. Thanks again!

**Comment by nekohasekai** [comment]
nightly-3: works

[vpnhotspot-6087321011019702511.log](https://github.com/Mygod/VPNHotspot/files/5056652/vpnhotspot-6087321011019702511.log)

nightly-4: works

[vpnhotspot-6544436594089315217.log](https://github.com/Mygod/VPNHotspot/files/5056658/vpnhotspot-6544436594089315217.log)

nightly-5: not work

[vpnhotspot-6733705495781572615.log](https://github.com/Mygod/VPNHotspot/files/5056662/vpnhotspot-6733705495781572615.log)

**Comment by Mygod** [comment]
Can you check if the following files exist?

* `/system/etc/ld.config.29.txt`
* `/system/etc/ld.config.vndk_lite.txt`
* `/system/etc/ld.config.txt`
* (or anything similar)

**Comment by Mygod** [comment]
I have a feeling that this might be fixed via f5ea58e35a1f5e63b82da9766a4d81678e41cf90. Please try if this works. If so, we can close this issue. Otherwise we might need to repeat the above (export debug info, check files).

https://mygod.be/resources/userscloud/z39i6qyke97v

**Comment by nekohasekai** [comment]
> Can you check if the following files exist?
> 
> * `/system/etc/ld.config.29.txt`
> * `/system/etc/ld.config.vndk_lite.txt`
> * `/system/etc/ld.config.txt`
> * (or anything similar)

Only `/system/etc/ld.config.29.txt` exists

> I have a feeling that this might be fixed via [f5ea58e](https://github.com/Mygod/VPNHotspot/commit/f5ea58e35a1f5e63b82da9766a4d81678e41cf90). Please try if this works. If so, we can close this issue. Otherwise we might need to repeat the above (export debug info, check files).
> 
> https://mygod.be/resources/userscloud/z39i6qyke97v

not work

[vpnhotspot-358897315119533858.log](https://github.com/Mygod/VPNHotspot/files/5060113/vpnhotspot-358897315119533858.log)

**Comment by Mygod** [comment]
Hmm can you export logcat for me?

**Comment by nekohasekai** [comment]
> Hmm can you export logcat for me?

[logcat.txt](https://github.com/Mygod/VPNHotspot/files/5060173/logcat.txt)

**Comment by Mygod** [comment]
Somehow this does not include the logcat from today. Can you attach the full logcat again?

**Comment by Mygod** [comment]
Oh found the error. Huh.

```
08-12 09:08:18.923 18184 18184 E AndroidRuntime: FATAL EXCEPTION: main
08-12 09:08:18.923 18184 18184 E AndroidRuntime: PID: 18184
08-12 09:08:18.923 18184 18184 E AndroidRuntime: java.lang.NoSuchMethodError: no static method "Lbe/mygod/librootkotlinx/RootServer;.main([Ljava/lang/String;)V"
08-12 09:08:18.923 18184 18184 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-12 09:08:18.923 18184 18184 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
```

**Comment by Mygod** [comment]
Everyone can go home now. I am an idiot.

**Comment by Mygod** [comment]
[v2.10.15](https://github.com/Mygod/VPNHotspot/releases/tag/v2.10.15) is released and should fix the bug.
