### ISSUE TITLE
在MIUI 13上 v2.13.4 無法使用 / Not working on MIUI 13 since v2.13.4

### ISSUE THREAD

**Issue by wongwengtim** [Mygod/VPNHotspot#339]
### 螢幕截圖 / Screenshot
![image](https://user-images.githubusercontent.com/32707423/155466271-e9e39dd9-849d-4329-bfc8-516f58b47766.png)

### 可能相關部分Log / Related Log
``` 02-24 13:24:19.436 10102 10102 W ip      : type=1400 audit(0.0:2510): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:20.267  4806  4959 I LongScreenshotUtils:  focus:true
02-24 13:24:20.268  4806  4959 I LongScreenshotUtils: current ratio width:1.0, height:1.0
02-24 13:24:20.448  4806  4806 I TetheringManager: unregisterTetheringEventCallback caller:be.mygod.vpnhotspot
02-24 13:24:20.468 10244 10244 W ip      : type=1400 audit(0.0:2513): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:20.903  4806  5224 I OpenGLRenderer: Davey! duration=9223371272082ms; Flags=0, FrameTimelineVsyncId=117193, IntendedVsync=764771776933, Vsync=764771776933, InputEventId=0, HandleInputStart=764772949082, AnimationStart=764772953509, PerformTraversalsStart=764773513405, DrawStart=764773771842, FrameDeadline=764791776932, FrameInterval=764772803821, FrameStartTime=8333333, SyncQueued=764774375071, SyncStart=764774428300, IssueDrawCommandsStart=764774550488, SwapBuffers=764775195123, FrameCompleted=9223372036854775807, DequeueBufferDuration=10364, QueueBufferDuration=499792, GpuCompleted=9223372036854775807, SwapBuffersCompleted=764775932363, DisplayPresentTime=0, 
02-24 13:24:21.373  4806  4857 D OpenGLRenderer: endAllActiveAnimators on 0x7633a0ba00 (RippleDrawable) with handle 0x777b8a40e0
02-24 13:24:23.504 10424 10424 W ip      : type=1400 audit(0.0:2528): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:24.560 10448 10448 W ip      : type=1400 audit(0.0:2529): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:25.584 10468 10468 W ip      : type=1400 audit(0.0:2530): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:26.644 10591 10591 W ip      : type=1400 audit(0.0:2536): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:27.672 10621 10621 W ip      : type=1400 audit(0.0:2537): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:28.696 10655 10655 W ip      : type=1400 audit(0.0:2540): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:29.748 10675 10675 W ip      : type=1400 audit(0.0:2541): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:30.772 10696 10696 W ip      : type=1400 audit(0.0:2542): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:31.824 10717 10717 W ip      : type=1400 audit(0.0:2543): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:32.900 10743 10743 W ip      : type=1400 audit(0.0:2554): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:33.713  4806  5224 D AppScoutStateMachine: 4806-ScoutStateMachinecreated
02-24 13:24:33.724 10764 10764 W ip      : type=1400 audit(0.0:2555): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:33.728 10762 10762 W ip      : type=1400 audit(0.0:2556): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:33.760  4806  4863 I ContentCatcher_TaplusBlackListHelper:  mActivities isEmpty
02-24 13:24:33.761  4806  4863 I ContentCatcher_TaplusBlackListHelper:  blackList size: 11 package is be.mygod.vpnhotspot isInTaplusWhiteList: true
02-24 13:24:33.924 10785 10785 W ip      : type=1400 audit(0.0:2557): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:34.711  4806  7751 W RootManager: java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize. For tests Dispatchers.setMain from kotlinx-coroutines-test module can be used
02-24 13:24:34.711  4806  7751 W RootManager: 	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:118)
02-24 13:24:34.711  4806  7751 W RootManager: 	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:96)
02-24 13:24:34.712  4806  7751 W RootManager: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:219)
02-24 13:24:34.712  4806  7751 W RootManager: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
02-24 13:24:34.712  4806  7751 W RootManager: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
02-24 13:24:34.712  4806  7751 W RootManager: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
02-24 13:24:34.713  4806  7751 W RootManager: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
02-24 13:24:34.715  4806  7751 W RootManager: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
02-24 13:24:34.715  4806  7751 W RootManager: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
02-24 13:24:34.715  4806  7751 W RootManager: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
02-24 13:24:34.715  4806  7751 W RootManager: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
02-24 13:24:34.715  4806  7751 W RootManager: 	at be.mygod.librootkotlinx.RootServer$Companion.rootMain(RootServer.kt:446)
02-24 13:24:34.716  4806  7751 W RootManager: 	at be.mygod.librootkotlinx.RootServer$Companion.main(RootServer.kt:366)
02-24 13:24:34.716  4806  7751 W RootManager: 	at be.mygod.librootkotlinx.RootServer.main(Unknown Source:2)
02-24 13:24:34.716  4806  7751 W RootManager: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-24 13:24:34.716  4806  7751 W RootManager: 	at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
02-24 13:24:34.716  4806  7751 W RootManager: Caused by: java.lang.IllegalStateException: The main looper is not available
02-24 13:24:34.717  4806  7751 W RootManager: 	at kotlinx.coroutines.android.AndroidDispatcherFactory.createDispatcher(HandlerDispatcher.kt:55)
02-24 13:24:34.717  4806  7751 W RootManager: 	at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:57)
02-24 13:24:34.717  4806  7751 W RootManager: 	at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:38)
02-24 13:24:34.717  4806  7751 W RootManager: 	at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:22)
02-24 13:24:34.717  4806  7751 W RootManager: 	at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:57)
02-24 13:24:34.718  4806  7751 W RootManager: 	at kotlinx.coroutines.DefaultExecutorKt.initializeDefaultDelay(DefaultExecutor.kt:18)
02-24 13:24:34.718  4806  7751 W RootManager: 	at kotlinx.coroutines.DefaultExecutorKt.<clinit>(DefaultExecutor.kt:13)
02-24 13:24:34.718  4806  7751 W RootManager: 	at kotlinx.coroutines.DefaultExecutorKt.getDefaultDelay(DefaultExecutor.kt:13)
02-24 13:24:34.718  4806  7751 W RootManager: 	at kotlinx.coroutines.internal.LimitedDispatcher.<init>(LimitedDispatcher.kt:19)
02-24 13:24:34.718  4806  7751 W RootManager: 	at kotlinx.coroutines.CoroutineDispatcher.limitedParallelism(CoroutineDispatcher.kt:101)
02-24 13:24:34.719  4806  7751 W RootManager: 	at kotlinx.coroutines.scheduling.DefaultIoScheduler.<clinit>(Dispatcher.kt:46)
02-24 13:24:34.719  4806  7751 W RootManager: 	at kotlinx.coroutines.Dispatchers.<clinit>(Dispatchers.kt:134)
02-24 13:24:34.719  4806  7751 W RootManager: 	at kotlinx.coroutines.Dispatchers.getIO(Dispatchers.kt:134)
02-24 13:24:34.719  4806  7751 W RootManager: 	at be.mygod.librootkotlinx.RootServer$Companion.rootMain(RootServer.kt:410)
02-24 13:24:34.720  4806  7751 W RootManager: 	... 4 more
02-24 13:24:34.731  4806  7751 W RootManager: Root process exited unexpectedly
02-24 13:24:34.932 10832 10832 W ip      : type=1400 audit(0.0:2558): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot
02-24 13:24:35.940 10840 10840 W ip      : type=1400 audit(0.0:2559): avc: granted { bind } for scontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tcontext=u:r:untrusted_app_29:s0:c223,c257,c512,c768 tclass=netlink_route_socket app=be.mygod.vpnhotspot

kotlinx.coroutines.JobCancellationException: Job was cancelled; job=CompletableDeferredImpl{Cancelled}@67b7865
	at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:703)
	at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:189)
	at be.mygod.librootkotlinx.RootServer$Callback$Ordinary.cancel(RootServer.kt:60)
	at be.mygod.librootkotlinx.RootServer.closeInternal(RootServer.kt:317)
	at be.mygod.librootkotlinx.RootServer.access$closeInternal(RootServer.kt:20)
	at be.mygod.librootkotlinx.RootServer$init$3.invokeSuspend(RootServer.kt:226)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### 裝置資訊 / Device Info

- 内核版本 / Kernel：4.19.113
- 裝置 / Device：Redmi K40
- 系統版本 / System Version：Android 12 (MIUI 13.0.3)
- Magisk：24.1 Zygisk
- 軟件版本 /  VPN Hotspot Version：v2.13.4 (Github)

**Comment by Mygod** [comment]
Does it work if you force stop the app and try again? Did any prior version of the app/your system work?

**Comment by wongwengtim** [comment]
Works fine on v2.13.3 and v2.13.2 but stop working since updated to v2.13.4. Performed many reboots/reinstall/clear app data but no luck.

**Comment by shichunjian** [comment]
确实有问题，我已经降级回可用版本了。

**Comment by Mygod** [comment]
Try this apk and see if that fixes it: https://we.tl/t-prNjiNaVd6

**Comment by wongwengtim** [comment]
I can confirm that this build fixed it and is working properly on the mentioned device. Really appreciate your help.

**Comment by Mygod** [comment]
@shichunjian Can you confirm as well? 

Regardless, this fix should be pushed in the next update should be pushed in the upcoming days.
