### ISSUE TITLE
Logcat spam of permission denied exceptions

### ISSUE THREAD

**Issue by taylorkline** [Mygod/VPNHotspot#352]
## Device

- OnePlus 9 Pro
- Android 11
- LineageOS

## Relevant Repeated Logcat

```
03-27 20:28:14.668 16239 16239 W ip      : type=1400 audit(0.0:242): avc: denied { bind } for scontext=u:r:untrusted_app:s0:c196,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c196,c256,c512,c768 tclass=netlink_route_socket permissive=0 b/155595000
03-27 20:28:14.673 16190 16235 W IpMonitor: java.io.IOException: Cannot bind netlink socket: Permission denied
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor$poll$3$1.invoke(IpMonitor.kt:201)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor$poll$3$1.invoke(IpMonitor.kt:200)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpNeighbourMonitor.processLines(IpNeighbourMonitor.kt:76)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor.poll(IpMonitor.kt:200)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor.work(IpMonitor.kt:156)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor.flush(IpMonitor.kt:145)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor$flushAsync$1.invokeSuspend(IpMonitor.kt:152)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
03-27 20:28:14.673 16190 16235 W IpMonitor:
03-27 20:28:14.673 16190 16235 W IpMonitor: java.io.IOException: Cannot bind netlink socket: Permission denied
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor$poll$3$1.invoke(IpMonitor.kt:201)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor$poll$3$1.invoke(IpMonitor.kt:200)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpNeighbourMonitor.processLines(IpNeighbourMonitor.kt:76)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor.poll(IpMonitor.kt:200)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor.work(IpMonitor.kt:156)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor.flush(IpMonitor.kt:145)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at be.mygod.vpnhotspot.net.monitor.IpMonitor$flushAsync$1.invokeSuspend(IpMonitor.kt:152)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
03-27 20:28:14.673 16190 16235 W IpMonitor: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

This happens every 5 seconds or so. 

## App Debug Log

[vpnhotspot-7193319927672206206.log](https://github.com/Mygod/VPNHotspot/files/8359014/vpnhotspot-7193319927672206206.log)

**Comment by Mygod** [comment]
You should try to switch to Monitor (root) or Poll (root) method in app settings.

**Comment by Mygod** [comment]
From what I can see, this error only appeared 3 times throughout (presumably when you are using the app) so I think it is fine? If you want to avoid this, you can either do that or download the GitHub version of this app.
