### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by luanyaolingwu** [Mygod/VPNHotspot#508]
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: motorola
[Device Model]: XT2125-4
[Display]: lineage_nio-userdebug 13 TQ3A.230805.001 826dac66b3
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_HK
[Process ID]: 11377
[CPU ABI]: none
[Package Name]: be.mygod.vpnhotspot
[Version Name]: 2.16.7
[Version Code]: 1007
[Error Type]: JVM
[Crash Time]: 2023-09-13T15:54:55.258
[Stack Trace]:
java.lang.SecurityException: Unknown calling package name 'be.mygod.vpnhotspot'.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at com.google.android.gms.common.internal.zzac.getService(com.google.android.gms:play-services-basement@@18.1.0:9)
	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(com.google.android.gms:play-services-basement@@18.1.0:14)
	at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(com.google.android.gms:play-services-basement@@18.1.0:2)
	at com.google.android.gms.common.internal.zzg.zzd(com.google.android.gms:play-services-basement@@18.1.0:1)
	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.1.0:4)
	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.1.0:3)
	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.1.0:31)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Mygod** [comment]
https://issuetracker.google.com/issues/37130301
