### ISSUE TITLE
QS tile crashes all system (Android Q)

### ISSUE THREAD

**Issue by p-knaulksmeg** [Mygod/VPNHotspot#98]
If you try to move custom quick tile to used tiles system will bootlooped
 
**Part of Logcat:**
```
04-26 01:28:27.755  4200  4224 E Icon    : Unable to load resource 0x7f080093 from pkg=be.mygod.vpnhotspot
04-26 01:28:27.755  4200  4224 E Icon    : android.content.res.Resources$NotFoundException: Drawable be.mygod.vpnhotspot:drawable/ic_de
vice_wifi_tethering with resource ID #0x7f080093
04-26 01:28:27.755  4200  4224 E Icon    : Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
04-26 01:28:27.755  4200  4224 E Icon    :      at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1137)

04-26 01:28:27.755  4200  4224 E Icon    :      at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1013)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1092)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.content.res.Resources.loadColorStateList(Resources.java:1062)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.content.res.TypedArray.getColorStateList(TypedArray.java:600)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.graphics.drawable.VectorDrawable.updateStateFromTypedArray(VectorDrawable.ja
va:743)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.graphics.drawable.VectorDrawable.applyTheme(VectorDrawable.java:612)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:674)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.content.res.Resources.getDrawableForDensity(Resources.java:906)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.content.res.Resources.getDrawable(Resources.java:845)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:369)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.graphics.drawable.Icon.loadDrawable(Icon.java:322)
04-26 01:28:27.755  4200  4224 E Icon    :      at com.android.systemui.qs.external.CustomTile.handleUpdateState(Unknown Source:26)
04-26 01:28:27.755  4200  4224 E Icon    :      at com.android.systemui.qs.tileimpl.QSTileImpl.handleRefreshState(Unknown Source:2)
04-26 01:28:27.755  4200  4224 E Icon    :      at com.android.systemui.qs.tileimpl.QSTileImpl$H.handleMessage(Unknown Source:142)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.os.Handler.dispatchMessage(Handler.java:106)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.os.Looper.loop(Looper.java:209)
04-26 01:28:27.755  4200  4224 E Icon    :      at android.os.HandlerThread.run(HandlerThread.java:67)
04-26 01:28:27.757   597   597 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/defaul
t in either framework or device manifest.
04-26 01:28:27.758  4200  4236 W Gralloc3: mapper 3.x is not supported
04-26 01:28:27.780   631   631 E HWComposer: presentAndGetReleaseFences: present failed for display 0: NotValidated (7)
04-26 01:28:27.819  4200  4200 D StatusBar: disable<e i a s b h r c s > disable2<q i n >
04-26 01:28:27.830   631   631 E HWComposer: presentAndGetReleaseFences: present failed for display 0: NotValidated (7)
04-26 01:28:27.848  4200  4200 I StatusBar/NavBarView: updateNavButtonIcons (b/113914868): home disabled=false mDisabledFlags=0
04-26 01:28:27.883  4200  4200 I chatty  : uid=10025(com.android.systemui) identical 3 lines
04-26 01:28:27.886  4200  4200 I StatusBar/NavBarView: updateNavButtonIcons (b/113914868): home disabled=false mDisabledFlags=0
04-26 01:28:27.899   631   631 E HWComposer: presentAndGetReleaseFences: present failed for display 0: NotValidated (7)
04-26 01:28:27.915   631   631 E HWComposer: presentAndGetReleaseFences: present failed for display 0: NotValidated (7)
04-26 01:28:27.924  4200  4200 D AndroidRuntime: Shutting down VM
04-26 01:28:27.925  4200  4200 E AndroidRuntime: FATAL EXCEPTION: main
04-26 01:28:27.925  4200  4200 E AndroidRuntime: Process: com.android.systemui, PID: 4200
04-26 01:28:27.925  4200  4200 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.dra
wable.Drawable$ConstantState android.graphics.drawable.Drawable.getConstantState()' on a null object reference
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.systemui.qs.external.CustomTile.lambda$handleUpdateState$0(Unkno
wn Source:0)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.systemui.qs.external.-$$Lambda$CustomTile$Oh-NzDEMM2yCWnVYbU2_DK
Tzaqo.get(Unknown Source:2)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.systemui.qs.tileimpl.QSIconViewImpl.updateIcon(Unknown Source:4)

04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.systemui.qs.tileimpl.QSIconViewImpl.setIcon(Unknown Source:80)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.systemui.qs.tileimpl.QSIconViewImpl.setIcon(Unknown Source:4)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.systemui.qs.tileimpl.QSTileBaseView.handleStateChanged(Unknown S
ource:70)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.systemui.qs.tileimpl.QSTileView.handleStateChanged(Unknown Sourc
e:0)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.systemui.qs.tileimpl.QSTileBaseView$H.handleMessage(Unknown Sour
ce:11)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:209)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7046)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java
:486)
04-26 01:28:27.925  4200  4200 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
04-26 01:28:27.927  1265  2440 W RescueParty: Noticed 5 events for UID 10025 in last 5 sec
04-26 01:28:27.929  1265  2440 W PackageManager: Incremented rescue level to FACTORY_RESET triggered by UID 10025
04-26 01:28:27.935  1265  2440 W RescueParty: Attempting rescue level FACTORY_RESET
```

**Comment by Mygod** [comment]
Thanks for reporting. I have notified Google of this issue: https://issuetracker.google.com/issues/131381057

Meanwhile, to fix this on your device without wiping your data, use `adb shell pm uninstall be.mygod.vpnhotspot` to uninstall this app, and avoid using Wi-Fi hotspot QS tile until this issue is resolved.

**Comment by Mygod** [comment]
I can no longer reproduce this on Q beta 3 emulator. Can you confirm that this has been fixed?

**Comment by p-knaulksmeg** [comment]
Not fixed, no bootloop but UI turns black

```
05-11 04:43:15.668 15742 15809 E Icon    : Unable to load resource 0x7f080093 from pkg=be.mygod.vpnhotspot
05-11 04:43:15.668 15742 15809 E Icon    : android.content.res.Resources$NotFoundException: Drawable be.mygod.vpnhotspot:drawable/ic_de
vice_wifi_tethering with resource ID #0x7f080093
05-11 04:43:15.668 15742 15809 E Icon    : Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
05-11 04:43:15.668 15742 15809 E Icon    :      at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1137)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1013)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1092)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.content.res.Resources.loadColorStateList(Resources.java:1062)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.content.res.TypedArray.getColorStateList(TypedArray.java:599)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.graphics.drawable.VectorDrawable.updateStateFromTypedArray(VectorDrawable.ja
va:758)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.graphics.drawable.VectorDrawable.applyTheme(VectorDrawable.java:627)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:674)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.content.res.Resources.getDrawableForDensity(Resources.java:906)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.content.res.Resources.getDrawable(Resources.java:845)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:370)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.graphics.drawable.Icon.loadDrawable(Icon.java:323)
05-11 04:43:15.668 15742 15809 E Icon    :      at com.android.systemui.qs.external.CustomTile.handleUpdateState(Unknown Source:26)
05-11 04:43:15.668 15742 15809 E Icon    :      at com.android.systemui.qs.tileimpl.QSTileImpl.handleRefreshState(Unknown Source:2)
05-11 04:43:15.668 15742 15809 E Icon    :      at com.android.systemui.qs.tileimpl.QSTileImpl$H.handleMessage(Unknown Source:142)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.os.Handler.dispatchMessage(Handler.java:107)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.os.Looper.loop(Looper.java:214)
05-11 04:43:15.668 15742 15809 E Icon    :      at android.os.HandlerThread.run(HandlerThread.java:67)
05-11 04:43:15.674 13753 13753 I Finsky  : [2] plc.b(7): Jobs in database: 1-1337 21-333333333 26-1414141414 29-29
05-11 04:43:15.675 13753 13753 I Finsky  : [2] pip.a(66): ConstraintMapping: 1-1337, 21-333333333,  -> L: 57357ms, D: 43604578ms, C: fa
lse, I: false, N: 1
05-11 04:43:15.676 13753 13753 I Finsky  : [2] pip.a(66): ConstraintMapping: 26-1414141414, 29-29,  -> L: 16776ms, D: 46776ms, C: false
, I: false, N: 0
05-11 04:43:15.678 13753 13753 I Finsky  : [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(42): Cancelling existing job wi
th id: 9002
05-11 04:43:15.693  1279  2122 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX
_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-11 04:43:15.693 15742 15742 D StatusBar: disable<e i a s b h r c s > disable2<q i n >
05-11 04:43:15.695 15742 15809 E Icon    : Unable to load resource 0x7f080093 from pkg=be.mygod.vpnhotspot
05-11 04:43:15.695 15742 15809 E Icon    : android.content.res.Resources$NotFoundException: Drawable be.mygod.vpnhotspot:drawable/ic_de
vice_wifi_tethering with resource ID #0x7f080093
05-11 04:43:15.695 15742 15809 E Icon    : Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
```

**Comment by Mygod** [comment]
Can you try a reinstall?

**Comment by p-knaulksmeg** [comment]
Already tried

**Comment by Mygod** [comment]
Well at least it doesn't crash the system now. Let's see how Google resolves this.

**Comment by p-knaulksmeg** [comment]
Fixed in beta 4

**Comment by Mygod** [comment]
Good news 👍

**Comment by p-knaulksmeg** [comment]
Same shit again on Q beta 6

**Comment by Mygod** [comment]
I were not able to reproduce this on emulator `sdk_gphone_x86_64-userdebug 10 QPP6.190730.005.B1 5775370 dev-keys`. If you can, please attach more information to Google's issue tracker (either append it to [my issue](https://issuetracker.google.com/issues/131381057) or open a new one).

**Comment by Mygod** [comment]
Okay I found the error and it seems to have changed.

```
20750-20750/com.android.systemui E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.systemui, PID: 20750
    com.android.systemui.shared.plugins.PluginManagerImpl$CrashWhilePluginActiveException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable$ConstantState android.graphics.drawable.Drawable.getConstantState()' on a null object reference
        at com.android.systemui.shared.plugins.PluginManagerImpl$PluginExceptionHandler.uncaughtException(PluginManagerImpl.java:426)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2181)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable$ConstantState android.graphics.drawable.Drawable.getConstantState()' on a null object reference
        at com.android.systemui.qs.external.CustomTile.lambda$handleUpdateState$0(CustomTile.java:319)
        at com.android.systemui.qs.external.-$$Lambda$CustomTile$Oh-NzDEMM2yCWnVYbU2_DKTzaqo.get(Unknown Source:2)
        at com.android.systemui.qs.tileimpl.QSIconViewImpl.updateIcon(QSIconViewImpl.java:101)
        at com.android.systemui.qs.tileimpl.QSIconViewImpl.setIcon(QSIconViewImpl.java:164)
        at com.android.systemui.qs.tileimpl.QSIconViewImpl.setIcon(QSIconViewImpl.java:97)
        at com.android.systemui.qs.tileimpl.QSTileBaseView.handleStateChanged(QSTileBaseView.java:215)
        at com.android.systemui.qs.tileimpl.QSTileView.handleStateChanged(QSTileView.java:119)
        at com.android.systemui.qs.tileimpl.QSTileBaseView$H.handleMessage(QSTileBaseView.java:341)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
